apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
  labels:
    app: openresty
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: openresty
  template:
    metadata:
      labels:
        app: openresty
    spec:
      containers:
        - name: app-three
          image: openresty/openresty:centos-rpm
          env:
            - name: NGINX_HOST
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              cpu: "0.2"
              memory: "300Mi"
            requests:
              cpu: "0.1"
              memory: "100Mi"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - name: cm-app-three
              mountPath: /usr/local/openresty/nginx/html/
      volumes:
        - name: cm-app-three
          configMap:
            name: cm-app-three