Vagrant.configure("2") do |config|

  config.vm.define "bjesseS" do |vm1|
    vm1.vm.box = "centos/7"
    vm1.vm.hostname = 'bjesseS'
    vm1.vm.box_url = "centos/7"
    vm1.vm.network "private_network", ip: "192.168.42.110"
    vm1.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "bjesseS"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.memory = 512
      v.cpus = 1
    end
    vm1.vm.provision "file", source: "~/.ssh/inception.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
    vm1.vm.provision "file", source: "~/.ssh/inception", destination: "/home/vagrant/.ssh/id_rsa"
    vm1.vm.provision "shell", run: "always", path: "scripts/scriptS.sh"

  end
  config.vm.define "bjesseSW" do |vm2|
    vm2.vm.box = "centos/8"
    vm2.vm.hostname = 'bjesseSW'
    vm2.vm.box_url = "centos/8"
    vm2.vm.network "private_network", ip: "192.168.42.111"
    vm2.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "bjesseSW"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.memory = 512
      v.cpus = 1
    end

    # vm1.vm.provision "file", source: "./test", destination: "/home/vagrant/test"
    vm2.vm.provision "file", source: "~/.ssh/inception.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
    vm2.vm.provision "file", source: "~/.ssh/inception", destination: "/home/vagrant/.ssh/id_rsa"
    vm2.vm.provision "shell", run: "always", path: "scripts/scriptSW.sh"
  end
end
